language: php
sudo: false
php:
- '7.1'
cache:
  directories:
  - "$HOME/.composer/cache"
before_script:
- composer install --prefer-dist --no-interaction
script:
- mkdir -p build/logs
- vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection
  `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`
notifications:
  email: false
